# author: 左志华
# date: 2022-08-12
#
# 测试
name: msys2-build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          path-type: inherit
          install: |
            mingw-w64-x86_64-gcc-fortran
            mingw-w64-x86_64-openblas
            mingw-w64-x86_64-fpm
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-python-ford

      - name: fpm test
        run: |
          fpm test

      - name: meson test
        run: |
          meson setup _build -Dbuildtype=debug
          meson test -C _build -v func_api

      - name: ford build
        run: |
          ford FORD.md

      - name: deploy pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.repository == 'zoziha/fffc' && ( startsWith( github.ref, 'refs/tags/' ) || github.ref == 'refs/heads/master' )
        with:
          folder: _build/ford
