# author: 左志华
# date: 2022-08-12
#
# 测试
name: msys2-build

on: [workflow_dispatch]

jobs:
  gfortran-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          path-type: inherit
          install: |
            mingw-w64-x86_64-gcc-fortran
            mingw-w64-x86_64-fpm

      - name: fpm test
        run: |
          fpm test
